lr_config:
  MultiStepLR:
    gamma: 0.5
    last_epoch: -1
    milestones:
    - 5
    - 10
    - 15
optim_config:
  AdamW:
    lr: 0.001
    weight_decay: 0.05


start_epoch: 0
nepoch: 11
test_epoch: 0
only_test_epoch: True
test_iters: 3000
print_freq: 100

batch_size: 8
max_depth: -1
sparsifier: "orb_sampler"
num_samples: 400
modality: "rgbd"
workers: 10
data: "nyudepthv2"